//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMaster
    {
        public int Id { get; set; }
        public string StockId { get; set; }
        public string StockName { get; set; }
        public Nullable<int> BuyPrice { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
